### ISSUE TITLE
Report Errors and Warnings(?) to ErrorReporting

### ISSUE THREAD

**Issue by frodebjerke** [unacast/logger#4]
As far as I understand, this package currently only reports Panics to ErrorReporting. Any logged Error and potentially also Warnings should also be reported for tracking.

**Comment by torbjornvatn** [comment]
Hmm, I thought ErrorReporting was for exception-like situations. We get `Exceptions` from Dataflow and `exit ≠ 0` events from Cloud Functions

**Comment by frodebjerke** [comment]
I guess where we have Error logging we want to know it no? Warnings I am okay with. If something is logged as error I want that to be because we should do something about it if not just arbitrarily passing by. Agree?

**Comment by torbjornvatn** [comment]
Error and Warnings are logged the "regular" way, so they show up in the logs. 
I think of ErrorReporting as a replacement for Sentry, hence just handling crashing behaviour like exceptions, panics and exit ≠ 0
